apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ac86ont0o-java-quarkus
  janus-idp.io/tekton: ac86ont0o-java-quarkus
  backstage.io/kubernetes-id: ac86ont0o-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ac86ont0o-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
